# Generated by Django 5.2.6 on 2025-12-29 14:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_managers'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='birthdate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='consent_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='consent_status',
            field=models.CharField(choices=[('not_consented', 'Not Consented Yet'), ('consented', 'Consented')], default='not_consented', max_length=20),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='parental_consent_file',
            field=models.FileField(blank=True, help_text='PDF file, max 10MB', null=True, upload_to='parental_consents/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])]),
        ),
    ]
