# Generated by Django 5.2.6 on 2025-12-30 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_birthdate_userprofile_consent_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='consent_status',
            field=models.CharField(choices=[('not_consented', 'Not Consented Yet'), ('pending_approval', 'Pending Admin Approval'), ('consented', 'Consented')], default='not_consented', max_length=20),
        ),
    ]
