# Generated by Django 5.2.6 on 2026-01-10 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_userprofile_email_verification_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='last_password_reset_request',
            field=models.DateTimeField(blank=True, help_text='Timestamp of last password reset request (24hr cooldown)', null=True),
        ),
    ]
