# Generated by Django 5.2.6 on 2026-01-15 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_userprofile_last_password_reset_request'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='verification_attempts',
            field=models.IntegerField(default=0, help_text='Number of failed verification attempts'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='verification_locked_until',
            field=models.DateTimeField(blank=True, help_text='Account locked until this time after too many failed attempts', null=True),
        ),
    ]
