# Generated by Django 5.2.6 on 2026-01-22 11:23

import django.core.validators
import storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_userprofile_verification_attempts_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='parental_consent_file',
            field=models.FileField(blank=True, help_text='PDF file, max 10MB', null=True, storage=storage.SupabaseStorage, upload_to='parental_consents/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])]),
        ),
    ]
