# Generated by Django 5.2.6 on 2026-01-26 04:01

import accounts.models
import django.core.validators
import storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_userprofile_parental_consent_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='parental_consent_file',
            field=models.FileField(blank=True, help_text='PDF file, max 10MB', null=True, storage=storage.SupabaseStorage, upload_to=accounts.models.user_consent_file_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])]),
        ),
    ]
