# Generated by Django 5.2.6 on 2025-12-11 03:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('middle_initial', models.CharField(blank=True, max_length=1, null=True)),
                ('suffix', models.CharField(blank=True, max_length=10, null=True)),
                ('G11_Batch', models.CharField(blank=True, max_length=9, null=True, validators=[django.core.validators.RegexValidator(regex='^\\d{4}-\\d{4}$')])),
                ('G12_Batch', models.CharField(blank=True, max_length=9, null=True, validators=[django.core.validators.RegexValidator(regex='^\\d{4}-\\d{4}$')])),
            ],
        ),
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ResearchPaper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('abstract', models.TextField()),
                ('publication_date', models.DateField()),
                ('grade_level', models.IntegerField(choices=[(11, 'Grade 11'), (12, 'Grade 12')])),
                ('strand', models.CharField(choices=[('STEM', 'Science, Technology, Engineering, and Mathematics (STEM)'), ('HUMSS', 'Humanities and Social Sciences (HUMSS)'), ('ABM', 'Accountancy, Business, and Management (ABM)')], max_length=100)),
                ('school_year', models.CharField(max_length=9, validators=[django.core.validators.RegexValidator(message='School year must be in the format YYYY-YYYY (e.g., 2023-2024)', regex='^\\d{4}-\\d{4}$')])),
                ('pdf_file', models.FileField(upload_to='research_papers/')),
                ('specialization', models.CharField(blank=True, choices=[('Medical', 'Medical'), ('Engineering', 'Engineering'), ('Information Technology', 'Information Technology (IT)')], help_text='Required if strand is STEM.', max_length=50, null=True)),
                ('author', models.ManyToManyField(to='research.author')),
                ('keywords', models.ManyToManyField(to='research.keyword')),
            ],
        ),
    ]
