# Generated by Django 5.2.6 on 2025-12-20 11:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keyword',
            name='word',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='researchpaper',
            name='keywords',
            field=models.ManyToManyField(blank=True, to='research.keyword'),
        ),
        migrations.AlterField(
            model_name='researchpaper',
            name='school_year',
            field=models.CharField(max_length=9, validators=[django.core.validators.RegexValidator(regex='^\\d{4}-\\d{4}$')]),
        ),
        migrations.AlterField(
            model_name='researchpaper',
            name='specialization',
            field=models.CharField(blank=True, choices=[('Medical', 'Medical'), ('Engineering', 'Engineering'), ('Information Technology', 'Information Technology')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='researchpaper',
            name='strand',
            field=models.CharField(choices=[('STEM', 'STEM'), ('HUMSS', 'HUMSS'), ('ABM', 'ABM')], max_length=10),
        ),
        migrations.AlterUniqueTogether(
            name='author',
            unique_together={('first_name', 'middle_initial', 'last_name', 'suffix')},
        ),
    ]
