# Generated by Django 5.2.6 on 2025-12-23 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0004_author_one_author_per_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='middle_initial',
            field=models.CharField(blank=True, max_length=1),
        ),
        migrations.AlterField(
            model_name='author',
            name='suffix',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
