# Generated by Django 5.2.6 on 2025-12-23 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0005_alter_author_middle_initial_alter_author_suffix'),
    ]

    operations = [
        migrations.CreateModel(
            name='Award',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='researchpaper',
            name='awards',
            field=models.ManyToManyField(blank=True, related_name='research_papers', to='research.award'),
        ),
    ]
