# Generated by Django 5.2.6 on 2025-12-29 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0006_award_researchpaper_awards'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='birthdate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
