# Generated by Django 5.2.6 on 2026-01-01 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0007_author_birthdate'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='keyword',
            options={'ordering': ['word']},
        ),
    ]
