# Generated by Django 5.2.6 on 2026-01-05 11:45

from django.db import migrations, models


def migrate_specialization_to_research_design(apps, schema_editor):
    """
    Migrate existing specialization data to research_design based on rules:
    - Grade 11 (all strands): QUALITATIVE
    - Grade 12 STEM with specialization: Map to new designs
    - Grade 12 non-STEM: SURVEY
    """
    ResearchPaper = apps.get_model('research', 'ResearchPaper')
    
    # Mapping old STEM specializations to new research designs
    # You can adjust these mappings based on what makes sense for your data
    specialization_mapping = {
        'Medical': 'SURVEY',
        'Engineering': 'EXPERIMENTAL',
        'Information Technology': 'CAPSTONE',
    }
    
    for paper in ResearchPaper.objects.all():
        if paper.grade_level == 11:
            # All Grade 11 papers become QUALITATIVE
            paper.research_design = 'QUALITATIVE'
        elif paper.grade_level == 12:
            if paper.strand == 'STEM' and paper.specialization:
                # Map old STEM specialization to new research design
                paper.research_design = specialization_mapping.get(
                    paper.specialization,
                    'SURVEY'  # Default fallback for any unmapped specializations
                )
            else:
                # Non-STEM Grade 12 papers default to SURVEY
                paper.research_design = 'SURVEY'
        else:
            # Fallback for any edge cases
            paper.research_design = 'QUALITATIVE'
        
        paper.save()
    
    print(f"✓ Migrated {ResearchPaper.objects.count()} research papers to new design system")


def reverse_migration(apps, schema_editor):
    """
    Reverse migration - attempt to restore specialization data.
    Note: This is lossy and won't perfectly restore the original data.
    """
    ResearchPaper = apps.get_model('research', 'ResearchPaper')
    
    # Reverse mapping (best effort)
    design_to_specialization = {
        'EXPERIMENTAL': 'Engineering',
        'CAPSTONE': 'Information Technology',
        'SURVEY': 'Medical',
    }
    
    for paper in ResearchPaper.objects.filter(strand='STEM', grade_level=12):
        if paper.research_design in design_to_specialization:
            paper.specialization = design_to_specialization[paper.research_design]
            paper.save()


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0008_alter_keyword_options'),
    ]

    operations = [
        # Step 1: Add research_design field (nullable temporarily)
        migrations.AddField(
            model_name='researchpaper',
            name='research_design',
            field=models.CharField(
                blank=True,
                null=True,
                max_length=50,
                choices=[
                    ('QUALITATIVE', 'Qualitative'),
                    ('SURVEY', 'Survey'),
                    ('EXPERIMENTAL', 'Experimental'),
                    ('CAPSTONE', 'Capstone')
                ],
                verbose_name='Research Design'
            ),
        ),
        
        # Step 2: Migrate data from specialization to research_design
        migrations.RunPython(
            migrate_specialization_to_research_design,
            reverse_code=reverse_migration
        ),
        
        # Step 3: Make research_design required (remove null=True, blank=True)
        migrations.AlterField(
            model_name='researchpaper',
            name='research_design',
            field=models.CharField(
                max_length=50,
                choices=[
                    ('QUALITATIVE', 'Qualitative'),
                    ('SURVEY', 'Survey'),
                    ('EXPERIMENTAL', 'Experimental'),
                    ('CAPSTONE', 'Capstone')
                ],
                verbose_name='Research Design'
            ),
        ),
        
        # Step 4: Remove old specialization field
        migrations.RemoveField(
            model_name='researchpaper',
            name='specialization',
        ),
    ]