# Generated by Django 5.2.6 on 2026-01-15 13:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0009_remove_researchpaper_specialization_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaperCitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cited_by_external', models.CharField(blank=True, max_length=500, null=True)),
                ('citation_date', models.DateField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('cited_by_paper', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cites', to='research.researchpaper')),
                ('paper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='citations', to='research.researchpaper')),
            ],
            options={
                'verbose_name': 'Paper Citation',
                'verbose_name_plural': 'Paper Citations',
            },
        ),
        migrations.CreateModel(
            name='PaperView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(blank=True, max_length=40, null=True)),
                ('viewed_at', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('paper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paper_views', to='research.researchpaper')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Paper View',
                'verbose_name_plural': 'Paper Views',
                'indexes': [models.Index(fields=['paper', 'user'], name='research_pa_paper_i_d00b30_idx'), models.Index(fields=['paper', 'session_key'], name='research_pa_paper_i_7d1d5d_idx')],
            },
        ),
    ]
