# Generated by Django 5.2.6 on 2026-01-22 00:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0010_papercitation_paperview'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PaperView',
        ),
    ]
