# Generated by Django 5.2.6 on 2026-01-22 11:23

import storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0011_delete_paperview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='researchpaper',
            name='pdf_file',
            field=models.FileField(storage=storage.SupabaseStorage, upload_to='research_papers/'),
        ),
    ]
