# Generated by Django 5.2.6 on 2026-01-22 11:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0012_alter_researchpaper_pdf_file'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='author',
            index=models.Index(fields=['last_name', 'first_name'], name='research_au_last_na_39701e_idx'),
        ),
        migrations.AddIndex(
            model_name='author',
            index=models.Index(fields=['G11_Batch'], name='research_au_G11_Bat_21e99d_idx'),
        ),
        migrations.AddIndex(
            model_name='author',
            index=models.Index(fields=['G12_Batch'], name='research_au_G12_Bat_9a88aa_idx'),
        ),
        migrations.AddIndex(
            model_name='keyword',
            index=models.Index(fields=['word'], name='research_ke_word_2f568d_idx'),
        ),
        migrations.AddIndex(
            model_name='researchpaper',
            index=models.Index(fields=['-publication_date'], name='research_re_publica_6db3d8_idx'),
        ),
        migrations.AddIndex(
            model_name='researchpaper',
            index=models.Index(fields=['strand'], name='research_re_strand_85dac8_idx'),
        ),
        migrations.AddIndex(
            model_name='researchpaper',
            index=models.Index(fields=['grade_level'], name='research_re_grade_l_32bfb8_idx'),
        ),
        migrations.AddIndex(
            model_name='researchpaper',
            index=models.Index(fields=['school_year'], name='research_re_school__cc81e3_idx'),
        ),
        migrations.AddIndex(
            model_name='researchpaper',
            index=models.Index(fields=['research_design'], name='research_re_researc_5bea99_idx'),
        ),
        migrations.AddIndex(
            model_name='researchpaper',
            index=models.Index(fields=['strand', 'research_design'], name='research_re_strand_188664_idx'),
        ),
        migrations.AddIndex(
            model_name='researchpaper',
            index=models.Index(fields=['title'], name='research_re_title_91a9c5_idx'),
        ),
    ]
