# Generated by Django 5.2.6 on 2026-01-29 14:36

import storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0013_author_research_au_last_na_39701e_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='researchpaper',
            name='pdf_file',
            field=models.FileField(max_length=300, storage=storage.SupabaseStorage, upload_to='research_papers/'),
        ),
    ]
