# Generated by Django 5.2.6 on 2026-01-30 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0014_alter_researchpaper_pdf_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='researchpaper',
            name='publication_date',
            field=models.DateField(help_text='Day will be automatically set to the 1st of the month'),
        ),
    ]
