# Generated by Django 5.2.6 on 2026-02-04 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0015_alter_researchpaper_publication_date'),
    ]

    operations = [
        # ========================================
        # ResearchPaper Indexes
        # ========================================
        
        # Index for filtering by school year (very common in your app)
        migrations.AddIndex(
            model_name='researchpaper',
            index=models.Index(fields=['school_year'], name='idx_paper_sy'),
        ),
        
        # Index for filtering by strand
        migrations.AddIndex(
            model_name='researchpaper',
            index=models.Index(fields=['strand'], name='idx_paper_strand'),
        ),
        
        # Index for filtering by grade level
        migrations.AddIndex(
            model_name='researchpaper',
            index=models.Index(fields=['grade_level'], name='idx_paper_grade'),
        ),
        
        # Index for filtering by research design
        migrations.AddIndex(
            model_name='researchpaper',
            index=models.Index(fields=['research_design'], name='idx_paper_design'),
        ),
        
        # Index for ordering by publication date (DESC) - most common sort
        migrations.AddIndex(
            model_name='researchpaper',
            index=models.Index(fields=['-publication_date'], name='idx_paper_pubdate'),
        ),
        
        # Composite index for common filter combinations
        migrations.AddIndex(
            model_name='researchpaper',
            index=models.Index(
                fields=['school_year', 'grade_level'], 
                name='idx_paper_sy_grade'
            ),
        ),
        
        # ========================================
        # Author Indexes
        # ========================================
        
        # Index for G11 batch filtering
        migrations.AddIndex(
            model_name='author',
            index=models.Index(fields=['G11_Batch'], name='idx_author_g11'),
        ),
        
        # Index for G12 batch filtering
        migrations.AddIndex(
            model_name='author',
            index=models.Index(fields=['G12_Batch'], name='idx_author_g12'),
        ),
        
        # Composite index for name sorting (last name, first name)
        migrations.AddIndex(
            model_name='author',
            index=models.Index(
                fields=['last_name', 'first_name'], 
                name='idx_author_name'
            ),
        ),
        
        # Index for user foreign key (for consent status queries)
        migrations.AddIndex(
            model_name='author',
            index=models.Index(fields=['user'], name='idx_author_user'),
        ),
        
        # ========================================
        # Keyword Indexes
        # ========================================
        
        # Index for keyword word field (for searching and sorting)
        migrations.AddIndex(
            model_name='keyword',
            index=models.Index(fields=['word'], name='idx_keyword_word'),
        ),
        
        # ========================================
        # Award Indexes
        # ========================================
        
        # Index for award name (for sorting)
        migrations.AddIndex(
            model_name='award',
            index=models.Index(fields=['name'], name='idx_award_name'),
        ),
    ]
