# Generated by Django 5.2.6 on 2026-02-05 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0016_add_performance_indexes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='researchpaper',
            options={'ordering': ['-publication_date', 'id']},
        ),
        migrations.RemoveIndex(
            model_name='author',
            name='research_au_last_na_39701e_idx',
        ),
        migrations.RemoveIndex(
            model_name='author',
            name='research_au_G11_Bat_21e99d_idx',
        ),
        migrations.RemoveIndex(
            model_name='author',
            name='research_au_G12_Bat_9a88aa_idx',
        ),
        migrations.RemoveIndex(
            model_name='keyword',
            name='research_ke_word_2f568d_idx',
        ),
        migrations.RemoveIndex(
            model_name='researchpaper',
            name='research_re_publica_6db3d8_idx',
        ),
        migrations.RemoveIndex(
            model_name='researchpaper',
            name='research_re_strand_85dac8_idx',
        ),
        migrations.RemoveIndex(
            model_name='researchpaper',
            name='research_re_grade_l_32bfb8_idx',
        ),
        migrations.RemoveIndex(
            model_name='researchpaper',
            name='research_re_school__cc81e3_idx',
        ),
        migrations.RemoveIndex(
            model_name='researchpaper',
            name='research_re_researc_5bea99_idx',
        ),
        migrations.RemoveIndex(
            model_name='researchpaper',
            name='research_re_strand_188664_idx',
        ),
        migrations.RenameIndex(
            model_name='researchpaper',
            new_name='idx_paper_title',
            old_name='research_re_title_91a9c5_idx',
        ),
    ]
